### ISSUE TITLE
Tuya WIFI Alarm Siren not appear in integration

### ISSUE THREAD

**Issue by alexreddy78** [tuya/tuya-home-assistant#150]
{
  "result": {
    "active_time": 1600715139,
    "biz_type": 18,
    "category": "sgbj",
    "create_time": 1600715139,
    "icon": "smart/icon/1528364694thahb9sok2l_0.png",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "",
    "name": "Сигнализация на кухне",
    "online": true,
    "owner_id": "16305239",
    "product_id": "DYgId0sz6zWlmmYu",
    "product_name": "Siren",
    "status": [
      {
        "code": "BatteryStatus",
        "value": "4"
      },
      {
        "code": "Alarmtype",
        "value": "9"
      },
      {
        "code": "AlarmPeriod",
        "value": 10
      },
      {
        "code": "AlarmSwitch",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "eu1600250372644kZmGd",
    "update_time": 1626270912,
    "uuid": "10082541bcddc2981908"
  },
  "success": true,
  "t": 1626337994973
}

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
{
  "result": {
    "category": "sgbj",
    "functions": [
      {
        "code": "Alarmtype",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "AlarmPeriod",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "AlarmSwitch",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "Alarmtype",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "BatteryStatus",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "AlarmSwitch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "AlarmPeriod",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1626338094685
}

**Comment by patrik-malina** [comment]
Same here:

{
"active_time": 1603897385,
"biz_type": 18,
"category": "wsdcg",
"create_time": 1603897385,
"icon": "smart/icon/1534401999ezpgt19rc8l_0.png",
"id": "02474500bcddc2690c74",
"ip": "46.17.124.38",
"lat": "45.4122199",
"local_key": "91423f3428b21f08",
"lon": "19.3027823",
"model": "NAS-AB02W0-1 Temperature and Humidity",
"name": "Alarm",
"online": true,
"owner_id": "17222907",
"product_id": "ymf4oruxqx0xlogp",
"product_name": "Siren",
"status": [],
"sub": false,
"time_zone": "+01:00",
"uid": "eu1602628501573H9rx2",
"update_time": 1626295238,
"uuid": "02474500bcddc2690c74"
},

**Comment by matzzzz** [comment]
Hi, I would also very much appreciate if the WiFi Siren as alexreddy78 have asked for above was added to the supported device. There is very few cheap Siren devices out on the market, and this WiFi siren is an ok product.
Regards
Matz

**Comment by patrik-malina** [comment]
Now with v1.5.0 it shows temperature and humidity, but no other info (siren activated, battery, tone, duration...

**Comment by alexreddy78** [comment]
@tsutsuku Dear Tsutsuku,

Kindly advise if there is any news regarding Siren/Alarm device to be shown in HA?

Regards

**Comment by frenck** [comment]
This has been addressed and added/fixed with the Home Assistant Core version of the integration and is pending release with Home Assistant 2021.11.

**Comment by alexreddy78** [comment]
@frenck @tsutsuku 
Dear Team,

Still not supported on 2021.11

Kindly advise

Regards!

**Comment by frenck** [comment]
> Kindly advise

Report a bug, the device category has been added.
