### ISSUE TITLE
New Device Request: PIR Deta Grid Connect Smart Compact PIR Sensor

### ISSUE THREAD

**Issue by Stupco** [tuya/tuya-home-assistant#61]
**Device normal info**
- Deta
- Grid Connect Smart Compact PIR Sensor

https://www.bunnings.com.au/deta-grid-connect-smart-compact-pir-sensor_p0129567

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
"active_time": 1625295948,
"biz_type": 0,
"category": "pir",
"create_time": 1625293805,
"icon": "smart/icon/ay1558866774161DZ6MV/1566282712ae29041f3ee.png",
"id": "21463430e098061e9aeb",
"ip": "159.196.116.205",
"lat": "-20",
"local_key": "e9aa722268e50349",
"lon": "140",
"name": "front_door_motion",
"online": true,
"owner_id": "11814174",
"product_id": "8mrw54ape8opgl69",
"product_name": "DET100HA",
"status": [],
"sub": false,
"time_zone": "+10:00",
"uid": "eu1587538607743cGw9R",
"update_time": 1625387083,
"uuid": "21463430e098061e9aeb"
}
],
"success": true,
"t": 1625390464994
}
2021-07-04 19:21:05 DEBUG (SyncWorker_10) [tuya iot] Response: {
"code": 2009,
"msg": "not support this device",
"success": false,
"t": 1625390465321
}

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
{"code":1010,"msg":"token invalid","success":false,"t":1625391007197}

**Comment by tsutsuku** [comment]
@Stupco The device needs to standardize, now it is fixed. You can try again.

**Comment by Stupco** [comment]
@tsutsuku Thanks for the response! A change in the logs, but still not showing up in HA:
`2021-07-08 19:40:27 DEBUG (Thread-8) [tuya iot] Response: {
"result": {
"client_id": "xxxx",
"expire_time": 7200,
"password": "xxxx",
"sink_topic": {
"device": "cloud/token/out/{device_id}"
},
"source_topic": {
"device": "cloud/token/in/fabxxxx"
},
"url": "ssl://m1.tuyaeu.com:8883",
"username": "cloud_xxxx"
},
"success": true,
"t": 1625737227476
}
2021-07-08 19:40:27 DEBUG (Thread-8) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
2021-07-08 19:40:28 DEBUG (SyncWorker_1) [tuya iot] Response: {
"result": [
{
"active_time": 1625295948,
"biz_type": 0,
"category": "pir",
"create_time": 1625293805,
"icon": "smart/icon/ay1558866774161DZ6MV/1566282712ae29041f3ee.png",
"id": "21463430e098061e9aeb",
"ip": "xxxx",
"lat": "xxxx",
"local_key": "xxxx",
"lon": "xxxx",
"name": "front_door_motion",
"online": true,
"owner_id": "11814174",
"product_id": "8mrw54ape8opgl69",
"product_name": "DET100HA",
"status": [],
"sub": false,
"time_zone": "+10:00",
"uid": "eu1587538607743cGw9R",
"update_time": 1625736879,
"uuid": "21463430e098061e9aeb"
}
],
"success": true,
"t": 1625737228333
}
`

**Comment by Stupco** [comment]
@tsutsuku this could be a problem that has a workaround fix as mentioned in [#153](https://github.com/tuya/tuya-home-assistant/issues/153#issuecomment-884058678)

I feel like the device is in EU and my account is possibly in Australia.

However, not confident enough to SSH into HA and try and brute force a fix as mentioned in the above link.
