### ISSUE TITLE
Tuya - Error While Get MQTT Config

### ISSUE THREAD

**Issue by CC91300** [tuya/tuya-home-assistant#741]
The problem
Receiving this error in the Core log:

[2021-12-14 07:02:53,221] [tuya-openmq] error while get mqtt config
2021-12-14 07:02:53 ERROR (Thread-9) [tuya_iot] error while get mqtt config

Note: All Tuya devices are working correctly.

What version of Home Assistant Core has the issue?
core-2021.12.1

What was the last working version of Home Assistant Core?
core-2021.12.0

What type of installation are you running?
Home Assistant OS

Integration causing the issue
Tuya

Link to integration documentation on our website
https://www.home-assistant.io/integrations/tuya/

Example YAML snippet
N/A
Anything in the logs that might be useful for us?
[2021-12-14 07:02:53,221] [tuya-openmq] error while get mqtt config
2021-12-14 07:02:53 ERROR (Thread-9) [tuya_iot] error while get mqtt config

**Comment by DIMMonchik** [comment]
The same error appeared after the update to version 2021.12.3

**Comment by MaxK99** [comment]
This is a recurring problem and/or related to:

https://github.com/tuya/tuya-home-assistant/issues/731
https://github.com/tuya/tuya-home-assistant/issues/733
https://github.com/tuya/tuya-home-assistant/issues/740

https://github.com/home-assistant/core/issues/59643
https://github.com/home-assistant/core/issues/59689
https://github.com/home-assistant/core/issues/59872
https://github.com/home-assistant/core/issues/59874
https://github.com/home-assistant/core/issues/59911
https://github.com/home-assistant/core/issues/61820

**Comment by dgthomson** [comment]
A workaround as posted elsewhere:

In **configuration.yaml** add (or confirm it contains:

```
system_log:
  fire_event: true
```

In **automations.yaml**, add:

```
- id: "TuyaIOT"
  alias: "TuyaIOT Restart"
  trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
      name: tuya_iot
  condition:
  - condition: template
    value_template: >-
      {{ "error while get mqtt config" in trigger.event.data.message[0] }}
  action:
  - service: homeassistant.reload_config_entry
    data:
      entity_id:
        - switch.living_room_lamp
```

**Important!** Change `switch.living_room_lamp` to the id of one of your system's own Tuya entities.

Works like a charm by resetting Tuya when `error while get mqtt config` occurs.

**Comment by CC91300** [comment]
> 在别处发布的解决方法：
> 
> 编辑：归功于[ResteNarquois](https://github.com/home-assistant/core/issues/61854#issuecomment-997197175)
> 
> 在**configuration.yaml**添加（或确认它包含：
> 
> ```
> system_log:
>   fire_event: true
> ```
> 
> 在**Automations.yaml 中**，添加：
> 
> ```
> - id: "TuyaIOT"
>   alias: "TuyaIOT Restart"
>   trigger:
>   - platform: event
>     event_type: system_log_event
>     event_data:
>       level: ERROR
>       name: tuya_iot
>   condition:
>   - condition: template
>     value_template: >-
>       {{ "error while get mqtt config" in trigger.event.data.message[0] }}
>   action:
>   - service: homeassistant.reload_config_entry
>     data:
>       entity_id:
>         - switch.living_room_lamp
> ```
> 
> **重要的！**更改`switch.living_room_lamp`为您系统自己的涂鸦实体之一的 id。
> 
> 通过在`error while get mqtt config`发生时重置 Tuya 来发挥魅力。

Thank you very much, according to your method has been solved

**Comment by dinan5** [comment]
I get this error message every two hours, when I reload Tuya it corrects it. I have done step 6 per the above.

**Comment by dgthomson** [comment]
Permanent fix for those happy to dig deep is here...

https://github.com/home-assistant/core/issues/62408#issuecomment-999648277

**Comment by viciovb** [comment]
> Permanent fix for those happy to dig deep is here...
> 
> [home-assistant/core#62408 (comment)](https://github.com/home-assistant/core/issues/62408#issuecomment-999648277)

it didn't work for me because I don't have any /usr/local/lib/python3.9/site-packages/tuya_iot folder in my HA

**Comment by psampatakos** [comment]
> > Permanent fix for those happy to dig deep is here...
> > [home-assistant/core#62408 (comment)](https://github.com/home-assistant/core/issues/62408#issuecomment-999648277)
> 
> it didn't work for me because I don't have any /usr/local/lib/python3.9/site-packages/tuya_iot folder in my HA

That is my case also. No tuya_iot directory

**Comment by kristiankjaer** [comment]
The fix worked for me. Running HA in docker. The directory/file should be there inside the docker - it was in my case at least (running HA 2021.11.1).
Copied out the file locally:
sudo docker cp homeassistant:/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py .
Modified the two lines (18 and 157) to:
18: TO_C_REFRESH_TOKEN_API_PRE = "/v1.0/token/"
157: response = self.get(
Copied back the file to the docker:
sudo docker cp ./openapi.py homeassistant:/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py
Works :)
I expect this to revert on next upgrade, however, I'll cross my fingers the tuya integration has included the fix by then.

**Comment by MaxK99** [comment]
[HA Release notes](https://www.home-assistant.io/blog/2021/12/11/release-202112/#release-2021126---december-27) indicate it's fixed in HA 2021.12.6.   Also see https://github.com/home-assistant/core/pull/62858

**Comment by dinan5** [comment]
I'm still getting this issue.  I'm at 2021.12.10

**Comment by JeroenTuinstra** [comment]
Just to remind everyone and keep this threat open. The issue is still there in version 2022.4.6.
I guess Tuya is not commited to making this work and their "big" announcement cooperating with Home Assistant was/is very short lift and a nice publicity stunt. 
Really disappointed with Tuya, and I don't understand why Home Assistant actually keeps including this integration as it clearly does not work for more than 6 months.

**Comment by outofsight** [comment]
same error on 2022.5
can add the integration, but no devices/entities found

**Comment by sschw56** [comment]
Same here on 2022.5.4
Just this error and no devices or entities. The connection and project on Tuya worked perfectly fine.

**Comment by markdepalma** [comment]
Having this same issue

**Comment by helldog136** [comment]
Issue still present:
https://community.home-assistant.io/t/tuya-integration-no-devices/421905

**Comment by philharmonie** [comment]
Having this issue as well

**Comment by preethaml7** [comment]
Still experiencing the same issue.

**Comment by 520xcy** [comment]
Having this issue

**Comment by bektorkhan** [comment]
**When** is this to be solved?
 Tuya has a big audience.....

Running ova HassOS in Vbox



2022-08-21 22:25:40.821 ERROR (Thread-3) [tuya_iot] error while get mqtt config
2022-08-21 22:25:40.836 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
    time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'

**Comment by Yiivgeny** [comment]
Same issue on core-2022.8.7

**Comment by koczis78** [comment]
Still the same on 2022.10.0

**Comment by frontendbuddy** [comment]
@bektorkhan 
> AttributeError: 'NoneType' object has no attribute 'expire_time'

This just feels like a field is missing when you get the IoT core trial extended.
I have exactly the same issue. It was working for 1 month and then the trial expired, I contacted Tuya and got it extended to 6 months although the Tuya Integration either does not recognize that change or the change on their side was to set the expire_time in a different field which is understood by their IoT Platform Web Interface but not by the integration. 

That's just my feeling, dunno what exactly to do with this. I've e-mailed Tuya about this and I'm awaiting for some response.
I don't know how to get into the /usr/local/lib/python3.10 to look around, my HA is on RPi 2.

**Comment by frontendbuddy** [comment]
Got it fixed by Tuya support after mailing them the details.

**Comment by rursache** [comment]
i'm having the same issue on 2022.11.4
EDIT: fixed by contacting tuya like @frontendbuddy said

**Comment by koczis78** [comment]
> Got it fixed by Tuya support after mailing them the details.

They only corrected it for you? or globally ? because I still have this problem.

**Comment by rursache** [comment]
> > Got it fixed by Tuya support after mailing them the details.
> 
> They only corrected it for you? or globally ? because I still have this problem.

unfortunately i had to contact tuya again to fix it, it seems they fix it per account 😓😒

**Comment by bprosman** [comment]
> Got it fixed by Tuya support after mailing them the details.

What did you exactly request from them ? Mine was expired as well and I requested a 6 month extension from them via the portal which is currently under review

**Comment by leoshusar** [comment]
I too wrote them and now I'm waiting for review. This is ridiculous.

I wasn't even worth saying "hello", lol
![SmartSelect_20221019_120903_Chrome.jpg](https://user-images.githubusercontent.com/13891066/196662950-083411ec-630e-4302-b26c-d3720a2446ca.jpg)

**Comment by bprosman** [comment]
> I too wrote them and now I'm waiting for review. This is ridiculous.
> 
> I wasn't even worth saying "hello", lol ![SmartSelect_20221019_120903_Chrome.jpg](https://user-images.githubusercontent.com/13891066/196662950-083411ec-630e-4302-b26c-d3720a2446ca.jpg)

Ah ok, same for me, extended (or at least requested) and now (also) awaiting review.

**Comment by frontendbuddy** [comment]
> > Got it fixed by Tuya support after mailing them the details.
> 
> They only corrected it for you? or globally ? because I still have this problem.

I didn't get any additional info about fixing the issue to wider audience so it seems that if you'll contact them then they will fix it for you.

> What did you exactly request from them ? Mine was expired as well and I requested a 6 month extension from them via the portal which is currently under review

screenshot of the ticket below

![image](https://user-images.githubusercontent.com/40119470/196772085-f4f82873-c606-4ea0-8d50-594c582385b5.png)

**Comment by bprosman** [comment]
Having the same issue, the trial is extended for 6 months. I did remove the integration from Home assistant, added it again and getting the same error as you do : 

2022-10-20 09:41:12.953 ERROR (Thread-3) [tuya_iot] error while get mqtt config
2022-10-20 09:41:12.980 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'
2022-10-20 09:41:22.905 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry bprosman@gmail.com for tuya
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 498, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 224, in async_unload_entry
hass_data.device_manager.mq.stop()
File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 212, in stop
self.client.disconnect()
AttributeError: 'NoneType' object has no attribute 'disconnect'

**Comment by bprosman** [comment]
> > > Got it fixed by Tuya support after mailing them the details.

Is it possible to mention your ticket # so that I can refer to that ?

**Comment by frontendbuddy** [comment]
Sure.

ID：T202210140110

**Comment by leoshusar** [comment]
So mine was approved too and the integration still doesn't work even after deleting and adding again.

**Comment by Sparky32** [comment]
I had the same , solved it by making new project in tuya iot . 
And put the new id and code in the tuya intergration. And all worked again

**Comment by bprosman** [comment]
> So mine was approved too and the integration still doesn't work even after deleting and adding again.
I reported that as well and this was their response , (so I will wait another 24 hours).

"Hello, your IOT Core is still under review, please wait patiently, it is expected to be available for normal use at the latest the day after tomorrow. (Note: The actual audit completion time is one day later than the time displayed on the page)"

The application shows as "Approved".

**Comment by leoshusar** [comment]
It's already been 10 hours since my approval and new project also doesn't work. But I'll give them another 14 hours.

Meanwhile I'm going to finally reflash some of my non-ESP Tuya devices to OpenBK7231T (Tasmota "clone"). It's just those lightbulbs which are quite easy to disassemble but nearly impossible to reassemble...

Edit: I had to write them again and they did *something*, now it finally works. He said just "try it again now".

**Comment by bprosman** [comment]
YEEEEYYYYYY , Mine started to work again this morning after I referred them to Frontendbuddy's ticket #, not sure if that helped. Most important it works and is extended for 6 months. Having that said decided to flash my smart plugs with Tasmota to become more independant.

**Comment by luizfeliperc** [comment]
I'm having the same problem and I don't know what else to do to try to solve it. The problem started last night and when redoing all the configuration the devices do not appear.
My trial was renewed for another 6 months, I created a new project and my devices still do not appear in the integration.


Home Assistant 2022.10.5

Logs: 

![image](https://user-images.githubusercontent.com/29809390/197403353-90c42c99-f6d4-4e21-948a-6eced02b9cb4.png)

![image](https://user-images.githubusercontent.com/29809390/197403369-95d4eba4-b990-4b9d-9b68-01c68f8d41f7.png)

**Comment by leoshusar** [comment]
You have to write them, for me new project also didn't work. They have to do something on their side.

**Comment by bprosman** [comment]
Raise a ticket and if you want refer to ours. 
Mine was :
T202210200012

**Comment by kingp0dd** [comment]
I'm experiencing the same issue.

- tried unlinking and relinking
- tried creating new Cloud project
- my Cloud API Services are already extended for 6 months yesterday

Logs are:

```

2022-10-24 16:39:22.855 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2022-10-24 16:39:22.873 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'

```

**Comment by dariokkk** [comment]
Hi. 
I have the same problem here.
It worked like a charm until last Friday.
The project was expired, I requested six extra months and it was approved.
I'm getting error on openmq.py in line 166. Before recreate the project the error was in line 161, like the other posts.
I did the sames steps than [kingp0dd](https://github.com/kingp0dd) and also added Device Status Notification in the new project.
I'm using HA 2022.10.5

**Comment by bprosman** [comment]
Even after the extension (6 months) was approved, for me it took at least 24 Hours before things started to work again.

**Comment by luizfeliperc** [comment]
Guys, I have good news.
It seems to me that the problem was really in the IoT Core trial. Even though they renewed for another 6 months, the warning message still persisted. After opening a ticket and reporting the problem, the integration started working again.

![image](https://user-images.githubusercontent.com/29809390/197421986-55d4c180-b6ed-4cbf-9a1f-acd8a9876a32.png)

![image](https://user-images.githubusercontent.com/29809390/197421993-ee6d104e-dabe-41ef-9d6e-2e0b38f1403d.png)

**Comment by kingp0dd** [comment]
It seems that you really need to open a ticket even after being renewed for
6 months. For now, i create a new account, which works too

**Comment by koczis78** [comment]
Hi, I contacted tuya support, they fixed something and the problem with `expire_time` no longer occurs, but there is a new, similar problem as @bprosman wrote about: `AttributeError: 'NoneType' object has no attribute 'disconnect`'. After another contact with support, they recommended deleting and create new the account in "Development Users". After doing this and reinstalling tuya integration in HA, it works great. My ticketID: T202210240056
![tuya2](https://user-images.githubusercontent.com/646734/197792542-eca3ab40-114c-4ec6-a1c3-529c2f16f625.png)
![tuya3](https://user-images.githubusercontent.com/646734/197793348-4770af8c-3208-48ac-9ada-5ac30115a22d.png)
![tuya4](https://user-images.githubusercontent.com/646734/197793083-d125dcab-b02b-4425-a990-f86ab31d49fa.png)

**Comment by kingp0dd** [comment]
Do you need a separate email for the new account?

**Comment by koczis78** [comment]
No, I deleted the existing ones and added the same again with new password.

**Comment by leoshusar** [comment]
I think this just confirms that Tuya has no intention to support Home Assistant anymore, when they advise to create new account instead of them fixing anything.

I say move from them as fast as you can, because once Tuya integration stops working (maybe HASS adds some breaking change or something, idk), they **won't** fix this integration and you will get stuck with the last working version.
I wouldn't even be surprised if they slowly limited their APIs to the point it won't be usable for HASS.

Look at the OpenBK7231T project and Tuya Cloudcutter, if you have devices with non ESP chips and want to flash them.

**Comment by kingp0dd** [comment]
Haven't heard of tuya cloud cutter before, have you had any luck with that?

**Comment by leoshusar** [comment]
Cloudcutter needs a device profile that's specific to each device model, somebody has to dump the firmware and send it to them. After they create the profile, it's possible for others to do 2 things:
 - just cut the cloud (for local controlling using e.g. LocalTuya)
 - flash alternative firmware (OpenBK7231T)

I've successfully flashed my 2 smart sockets with it, there was already functional profile for mine.
I also have RGB bulbs, but there is no profile for my model yet, so I dumped the firmware and now I'm waiting for profile. Unfortunately they are not much active at this moment, but it's worth a try, it's not possible to break anything using wrong profile.

I can also flash them via UART, but reassembling those bulbs is almost impossible.

Another way is to replace the whole chip with ESP and then use Tasmota or ESPHome, I have done this to one device too.

**Comment by bprosman** [comment]
> Cloudcutter needs a device profile that's specific to each device model, somebody has to dump the firmware and send it to them. After they create the profile, it's possible for others to do 2 things:
> 
> * just cut the cloud (for local controlling using e.g. LocalTuya)
> * flash alternative firmware (OpenBK7231T)
> 
> I've successfully flashed my 2 smart sockets with it, there was already functional profile for mine. I also have RGB bulbs, but there is no profile for my model yet, so I dumped the firmware and now I'm waiting for profile. Unfortunately they are not much active at this moment, but it's worth a try, it's not possible to break anything using wrong profile.
> 
> I can also flash them via UART, but reassembling those bulbs is almost impossible.
> 
> Another way is to replace the whole chip with ESP and then use Tasmota or ESPHome, I have done this to one device too.

My older sockets I could reflash with Tasmota. I also have a bunch of GU10 Warm White / Cool White , they internally have a : ESP8285 and BP5778.

**Comment by dariokkk** [comment]
Hi guys.
Its working again for me.
After receive the extention time I revoked the IoT core permission in the project, then added it again.
About six hours after this, it started to work again. If I had just wait, maybe the result was the same.
Some devices I renamed in the Smart Life APP changed their names after reintegration. I had to adjust my red node flows and everything is fine now.

![tuya_project](https://user-images.githubusercontent.com/112438913/198013286-fc227be5-9d86-4359-8ba3-9ceb274e00c0.png)

**Comment by Murada99** [comment]
Same for me.
Opening the Iot Platform I saw that the trial period was expired (cloud menu/ cloud services)

![image](https://user-images.githubusercontent.com/48693406/203651633-d62a8230-3cda-410f-821d-d7a996885bc7.png)

Button was available to extend the period, I just clicked the button, asked for an extension of 6 months and now after reload the integration and restart HA, all entities are back.

I can see that the end date was extended.

![image](https://user-images.githubusercontent.com/48693406/203651965-98803c70-449d-4c88-80bb-21ba431c60f8.png)

More info :  https://github.com/home-assistant/core/issues/80278

**Comment by rmroc451** [comment]
> Same for me. Opening the Iot Platform I saw that the trial period was expired (cloud menu/ cloud services)
> 
> ![image](https://user-images.githubusercontent.com/48693406/203651633-d62a8230-3cda-410f-821d-d7a996885bc7.png)
> 
> Button was available to extend the period, I just clicked the button, asked for an extension of 6 months and now after reload the integration and restart HA, all entities are back.
> 
> I can see that the end date was extended.
> 
> ![image](https://user-images.githubusercontent.com/48693406/203651965-98803c70-449d-4c88-80bb-21ba431c60f8.png)
> 
> More info : [home-assistant/core#80278](https://github.com/home-assistant/core/issues/80278)

Ditto, just did the same thing.

**Comment by Phunixx** [comment]
Running HA on a VM on a Synology NAS:
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

![Knipsel](https://user-images.githubusercontent.com/77805692/205638778-6200233f-435b-49e7-86be-2052a02cee6c.JPG)

If i restart HA it works a few hours, but after a while same errors, lamps not turning on or off.
Already re registered tuya api stuff, unlinked and relinked account....
Still no avail

**Comment by dgthomson** [comment]
> Running HA on a VM on a Synology NAS: Home Assistant 2022.11.5 Supervisor 2022.11.2 Operating System 9.3 Frontend 20221108.0 - latest
> 
> ![Knipsel](https://user-images.githubusercontent.com/77805692/205638778-6200233f-435b-49e7-86be-2052a02cee6c.JPG)
> 
> If i restart HA it works a few hours, but after a while same errors, lamps not turning on or off. Already re registered tuya api stuff, unlinked and relinked account.... Still no avail

have you added the workaround posted [here](https://github.com/tuya/tuya-home-assistant/issues/741#issuecomment-997349674)?

**Comment by Phunixx** [comment]
Thx, will try

**Comment by 175009** [comment]
`Dec 26 11:27:12 homepc homeassistant[2480]: [2022-12-26 12:27:12,199] [tuya-openmq] error while get mqtt config
Dec 26 11:27:12 homepc homeassistant[2480]: 2022-12-26 12:27:12.199 ERROR (Thread-7) [tuya_iot] error while get mqtt config
Dec 26 11:27:12 homepc homeassistant[2480]: 2022-12-26 12:27:12.222 ERROR (Thread-7) [root] Uncaught thread exception
Dec 26 11:27:12 homepc homeassistant[2480]: Traceback (most recent call last):
Dec 26 11:27:12 homepc homeassistant[2480]:   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Dec 26 11:27:12 homepc homeassistant[2480]:     self.run()
Dec 26 11:27:12 homepc homeassistant[2480]:   File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
Dec 26 11:27:12 homepc homeassistant[2480]:     time.sleep(self.mq_config.expire_time - 60)
Dec 26 11:27:12 homepc homeassistant[2480]: AttributeError: 'NoneType' object has no attribute 'expire_time'`

**Comment by recklezz** [comment]
So do we need to manually extend this trial every 6 months?

**Comment by Sparky32** [comment]
> So do we need to manually extend this trial every 6 months?  

Yes

**Comment by Schlicki** [comment]
Have the same issue now. Is the solution still to extend the project via tuya support?

**Comment by rmroc451** [comment]
They have a self service request section now on your tuya account.  Last two times, that's what I've done. Takes a day or so for them to approve and apply.
